FROM ruby:3.3.0
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg build-essential libvips42 libpq-dev libssl-dev vim libimage-exiftool-perl
RUN mkdir /myapp
WORKDIR /myapp
RUN gem install bundler
ADD . /myapp